name: Deploy and Run .NET WebAPI

on:
  push:
    branches:
      - master  # Adjust this based on your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Adjust to your .NET version

    - name: Restore dependencies
      run: dotnet restore DailyPulse.WebAPI/DailyPulse.WebAPI.csproj

    - name: Build
      run: dotnet build DailyPulse.WebAPI/DailyPulse.WebAPI.csproj --configuration Release --no-restore

    - name: Publish WebAPI
      run: |
        dotnet publish DailyPulse.WebAPI/DailyPulse.WebAPI.csproj -c Release -o ./publish --no-build

    - name: Copy Published Files to Server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./publish/*
        target: /home/${{ secrets.SERVER_USER }}/Downloads/testpublish
        port: 22

    - name: Run WebAPI on Remote Server
      run: |
        ssh -t -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/${{ secrets.SERVER_USER }}/Downloads/testpublish

        # Kill any running process of the app
        pids=$(pgrep -f "dotnet DailyPulse.WebAPI.dll")
        if [ -n "$pids" ]; then
          echo "Killing existing app processes: $pids"
          sudo kill -9 $pids
        else
          echo "No existing app process found"
        fi

        # Make sure the .dll file exists
        if [ -f "DailyPulse.WebAPI.dll" ]; then
          echo "Starting new instance of WebAPI..."
          dotnet DailyPulse.WebAPI.dll --urls "http://192.168.121.17:5000"
        else
          echo "Error: WebAPI application file not found!"
          exit 1
        fi
        EOF
  