name: Deploy and Run .NET WebAPI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      run: ls -R

    - name: Find .csproj files
      run: find . -name "*.csproj"

    - name: Verify checkout
      run: |
        git branch
        git log -1
        ls -la DailyPulse.WebAPI/ || echo "Directory not found"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore DailyPulse.WebAPI.csproj
      working-directory: ./DailyPulse.WebAPI

    - name: Build
      run: dotnet build DailyPulse.WebAPI.csproj --configuration Release --no-restore
      working-directory: ./DailyPulse.WebAPI

    - name: Publish WebAPI
      run: dotnet publish DailyPulse.WebAPI.csproj -c Release -o ./publish --no-build
      working-directory: ./DailyPulse.WebAPI

    - name: Copy Published Files to Server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./DailyPulse.WebAPI/publish/*
        target: /home/${{ secrets.SERVER_USER }}/Downloads/testpublish
        port: 22

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add remote host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Run WebAPI on Remote Server
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/${{ secrets.SERVER_USER }}/Downloads/testpublish/DailyPulse.WebAPI/publish || exit 1
        pids=$(pgrep -f "dotnet DailyPulse.WebAPI.dll")
        if [ -n "$pids" ]; then
          echo "Killing existing app processes: $pids"
          sudo kill -9 $pids
        else
          echo "No existing app process found"
        fi
        if [ -f "DailyPulse.WebAPI.dll" ]; then
          echo "Starting new instance of WebAPI..."
          nohup dotnet DailyPulse.WebAPI.dll --urls "http://192.168.121.17:5000" &
        else
          echo "Error: WebAPI application file not found!"
          exit 1
        fi
        EOF
